modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="wondercraft"
version="${file.jarVersion}"
displayName="Wonder Craft"
logoFile="examplemod.png"
credits="Mod by ValorantJay"
authors="ValorantJay"
description='''
My Mod
'''
[[dependencies.wondercraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wondercraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"